[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    electroniccats/MPU6050 @ ^1.3.0
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    NewPing
    arduino-libraries/Servo
build_flags =
    -Wall
    -DLOW_LEVEL_ECU
